apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-deployment
spec:
  replicas: 2  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: youtube
  template:
    metadata:
      labels:
        app: youtube
    spec:
      containers:
      - name: youtube-container
        image: anrs125/youtube:latest 
        ports:
        - containerPort: 80
